--- 
pool: 
  vmImage: ubuntu-16.04
stages: 
  - 
    displayName: ~
    jobs: 
      - 
        displayName: "Build Nuget packages"
        job: BuildNuget
        steps: 
          - 
            inputs: 
              command: restore
              feedsToUse: select
              projects: "**/*.csproj"
            task: DotNetCoreCLI@2
          - 
            inputs: 
              arguments: "--configuration $(BuildConfiguration)"
              command: build
              projects: "**/*.csproj"
            task: DotNetCoreCLI@2
          - 
            inputs: 
              command: pack
              packagesToPack: "**/*.csproj"
              versioningScheme: "off"
            task: DotNetCoreCLI@2
          - 
            inputs: 
              command: push
              nuGetFeedType: internal
              packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
              publishVstsFeed: f50482f5-11a3-4eea-9ab0-2b4c997bd0e2
            task: DotNetCoreCLI@2
        variables: 
          BuildConfiguration: release
    stage: Build_Stage
trigger: 
  - master
